// <auto-generated />
namespace Unicorn.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class configure_many_to_many_roles_to_permissions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(configure_many_to_many_roles_to_permissions));
        
        string IMigrationMetadata.Id
        {
            get { return "201708151434549_configure_many_to_many_roles_to_permissions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
