language: node_js
node_js:
- '8.1'
branches:
  only:
  - develop
before_script:
- cd frontend
- npm install -g @angular/cli
- npm install
script:
- ng build --prod
after_success:
  "curl --ftp-create-dirs -u $FTP_USER:$FTP_PASSWORD ftp://50.31.20.254/Unicorn/frontend"
notifications:
  email:
    on_failure: change
    on_success: change