language: node_js
node_js:
- '8.1'
branches:
  only:
  - develop
before_script:
- cd frontend
- npm install -g @angular/cli
- npm install
script:
- ng build --prod
after_success:
  - apt-get install ncftp
  - cd dist
  - ncftpput -R -v -u $FTP_USER -p $FTP_PASSWORD 50.31.20.254 Unicorn/frontend ./
notifications:
  email:
    on_failure: change
    on_success: change